language: node_js

node_js:
  - "lts/*"

cache:
  directories:
    - node_modules

install:
  - npm install -q
  - wget http://collection.b0.upaiyun.com/softwares/upx/upx-linux-amd64-v0.2.3 -O upx
  - chmod 755 upx

script:
  - npm run build
  - rm -rf deploy
  - mkdir -p deploy/project
  - mv dist deploy/project/imgbed

deploy:
  - provider: script
    skip-cleanup: true
    script: ./upx --auth $UPX_AUTH sync -delete --strong ./deploy
  - provider: pages
    skip-cleanup: true
    keep-history: true
    local-dir: deploy/project/imgbed
    target-branch: $GITHUB_BRANCH
    github-token: $GITHUB_TOKEN
    verbose: true

branches:
  only:
    - master
